lst1=["Apple","Banana","Cherry","Mango","Grapes"]
print(lst1)
print(lst1[0]) 
print(lst1[1:4]) 
print(lst1[:3]) 
lst1.append("Orange") 
print(lst1)
lst1.insert(2,"Pineapple") 
print(lst1)
lst1.remove("Banana") 
print(lst1)
lst1.pop() 
print(lst1)
lst1[1]="Strawberry" 
print(lst1)
print("")

a=("Apple","Banana","Cherry","Mango","Grapes") 
print(a)